GET http://localhost:3000/acronyms/list/acronym?from=50&limit=10&search=W

###
POST http://localhost:3000/acronyms/register
Content-Type: application/json

{
    "username": "TestUser1",
    "password": "TestPassword",
    "role": "admin"
}

###
POST http://localhost:3000/acronyms/login/
Content-Type: application/json

{
    "username": "TestUser1",
    "password": "TestPassword"
}

###
GET http://localhost:3000/acronyms/all

###
GET http://localhost:3000/acronyms/hydrate

###
GET http://localhost:3000/acronyms/SampleACRONYM

###
GET http://localhost:3000/acronyms/random/5

###
POST http://localhost:3000/acronyms/
Content-Type: application/json

{
    "acronym": "SampleACRONYM",
    "fullForm": "sample definition"
}

###
PUT http://localhost:3000/acronyms/SampleACRONYM
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiVGVzdFVzZXIxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjMxODkwMzE1fQ.RD8ISbjd9LfB9RHo8Z3U795c9JHLeMFM1m7AK_Os1Xw
Content-Type: application/json

{
    "fullForm": "Updated def"
}

###
DELETE http://localhost:3000/acronyms/AFK
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiVGVzdFVzZXIxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjMxODkwMzE1fQ.RD8ISbjd9LfB9RHo8Z3U795c9JHLeMFM1m7AK_Os1Xw