GET http://localhost:3000/acronyms/acronym?from=50&limit=10&search=:search

// checked and working:
DELETE http://localhost:3000/acronyms/acronym/:acronym
###
PATCH http://localhost:3000/acronyms/acronym/:acronym
###
POST http://localhost:3000/acronyms/acronym
Content-Type: application/json

{
    "acronym": "TDAdDB",
    "fullForm": "Test Dodawania Akronimu do DB"
}

###
GET http://localhost:3000/acronyms/random/:count?
###
GET http://localhost:3000/acronyms/acronym/:TDAdDB
###
GET http://localhost:3000/acronyms/hydrate
###
GET http://localhost:3000/acronyms/

