GET http://localhost:3000/acronyms/list?from=50&limit=10&search=:search
###
PUT http://localhost:3000/acronyms/:acronym

{
    "acronym": "TDAdDB2001",
    "fullForm": "Updated"
}

###
GET http://localhost:3000/acronyms/random/:count?
###
POST http://localhost:3000/acronyms/login


//WORKING FINE:
###
GET http://localhost:3000/acronyms/

###
GET http://localhost:3000/acronyms/hydrate

###
GET http://localhost:3000/acronyms/TDAdDB2005

###
POST http://localhost:3000/acronyms/
Content-Type: application/json

{
    "acronym": "TDAdDB2001",
    "fullForm": "Test Dodawania Akronimu do DB1"
}

###
DELETE http://localhost:3000/acronyms/NEW TEST 2

